### ISSUE TITLE
"The Art of Agile Development" : erreur sur les auteurs, ou erreur sur le titre ?

### ISSUE THREAD

**Issue by sroccaserra** [arpinum/awesome#1]
Salut Arpinum,

Super liste, merci !

Je crois que le bouquin "The Art of Agile Development: Pragmatic Guide to Agile Software Development" est de Shane Warden & James Shore (vu ici <http://shop.oreilly.com/product/9780596527679.do>).

Lisa Crispin et Janet Gregory ont écrit "Agile Testing: A Practical Guide for Testers and Agile Teams", qui vaut le détour aussi d'après ce que j'ai entendu.

Cheers!
Sébastien.

**Comment by sroccaserra** [comment]
@BodySplash, @lilobase, qu'en pensez-vous ?

**Comment by couillardcharles** [comment]
Salut @sroccaserra, bien vu 👍  
Je viens de le corriger.
